services:
  thingspan:
    image: ghcr.io/teemosun/thingspan:latest
    container_name: thingspan
    ports:
      - "19234:8000"
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
