"""drop category icon

Revision ID: 666f352524fb
Revises: a43a5729bc18
Create Date: 2026-08-09 19:54:58.373998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '666f352524fb'
down_revision: Union[str, None] = 'a43a5729bc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
