"""asset icon

Revision ID: 9877d37e23cf
Revises: ddad33600d6d
Create Date: 2026-08-09 21:24:04.094780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9877d37e23cf'
down_revision: Union[str, None] = 'ddad33600d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'icon')
    # ### end Alembic commands ###
