"""add reminder sent flag

Revision ID: a43a5729bc18
Revises: 8160e1cf60b3
Create Date: 2026-08-09 19:34:47.735636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a43a5729bc18'
down_revision: Union[str, None] = '8160e1cf60b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder_logs', sa.Column('sent', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder_logs', 'sent')
    # ### end Alembic commands ###
