"""warranty months per asset

Revision ID: ddad33600d6d
Revises: 2603a2cb4f14
Create Date: 2026-08-09 20:10:43.670059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ddad33600d6d'
down_revision: Union[str, None] = '2603a2cb4f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('assets', sa.Column('warranty_months', sa.Integer(), nullable=True))
    # 回填：已有保修结束日期的资产，按（结束日 - 购买日）/ 30 天推算月数，保持提醒逻辑不中断
    op.execute(
        """
        UPDATE assets
        SET warranty_months = CAST(ROUND((julianday(warranty_end_date) - julianday(purchase_date)) / 30.0) AS INT)
        WHERE warranty_end_date IS NOT NULL AND purchase_date IS NOT NULL
          AND warranty_end_date > purchase_date
        """
    )
    op.drop_column('categories', 'warranty_months')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('warranty_months', sa.INTEGER(), nullable=True))
    op.drop_column('assets', 'warranty_months')
    # ### end Alembic commands ###
